import { Component, Inject, OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
import { MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog';
import { CoreService } from '../services/core.service';
import { ClientService } from '../services/client.service';

@Component({
  selector: 'app-cl-add-edit',
  templateUrl: './cl-add-edit.component.html',
  styleUrls: ['./cl-add-edit.component.css'],
})
export class ClAddEditComponent implements OnInit {
  clForm: FormGroup;

  agence: string[] = [
    'AGENCE NABEUL (00)                    ',
    'AGENCE HAMMAMET (01)                  ',
    'AGENCE BIR MCHERGUA (02)              ',
    'AGENCE GROMBALIA (03)                 ',
    'AGENCE MENZEL BOUZELFA (04)           ',
    'AGENCE KORBA (05)                     ',
    'AGENCE EL MANAR (06)                  ',
    'AGENCE BAB SOUIKA (07)                ',
    'AGENCE UTIQUE (08)                    ',
    'AGENCE HAMMAM SOUSSE (09)             ',
    'AGENCE KAIROUAN (10)                  ',
    'AGENCE OUESLATIA (11)                 ',
    'AGENCE TEBOULBA (12)                  ',
    'AGENCE JAMEL ABDENNACEUR (13)         ',
    'AGENCE SFAX 5 AOUT (14)               ',
    'AGENCE LES BERGES DU LAC (15)         ',
    'AGENCE SOUSSE KHEZAMA (16)            ',
    'AGENCE AVENUE DE PARIS II (17)        ',
    'AGENCE HAFSIA (18)                    ',
    'AGENCE CHARGUIA II (19)               ',
    'AGENCE SOUSSE (20)                    ',
    'AGENCE MAHDIA I (21)                  ',
    'AGENCE SOUSSE NORD (22)               ',
    'AGENCE MONASTIR (23)                  ',
    'AGENCE KSAR HELLAL (24)               ',
    'AGENCE KALAA SGHIRA (25)              ',
    'AGENCE MSAKEN (26)                    ',
    'AGENCE KSIBET EL MEDIOUNI (27)        ',
    'AGENCE SOUSSE CORNICHE (28)           ',
    'AGENCE SIDI BOUALI (29)               ',
    'AGENCE TOZEUR (30)                    ',
    'AGENCE SFAX CENTRE (31)               ',
    'AGENCE SFAX 2000 (32)                 ',
    'AGENCE DJERBA HOUMT ESSOUK (33)       ',
    'AGENCE SFAX HABIB THAMEUR (34)        ',
    'AGENCE SFAX CITE EL HABIB (35)        ',
    'AGENCE SFAX EL HILAL (36)             ',
    'AGENCE BIR ALI BEN KHELIFA (37)       ',
    'AGENCE FOIRE DE SFAX (38)             ',
    'AGENCE SFAX HARZALLAH (40)            ',
    'AGENCE GABES (41)                     ',
    'AGENCE SFAX MARLBURG (42)             ',
    'AGENCE SFAX HACHED (43)               ',
    'AGENCE SFAX GREMDA (44)               ',
    'AGENCE SFAX NORD (45)                 ',
    'AGENCE SFAX MEDINA (46)               ',
    'AGENCE MAHRES (47)                    ',
    'AGENCE SAKIET EZZIT (48)              ',
    'AGENCE EL HENCHA (49)                 ',
    'AGENCE BIZERTE (50)                   ',
    'CENTRE D AFFAIRES DE TUNIS (51)       ',
    'AGENCE MEGRINE (52)                   ',
    'AGENCE EL ALIA (53)                   ',
    'AGENCE BEJA (54)                      ',
    'AGENCE MATEUR (55)                    ',
    'AGENCE GALAXY (56)                    ',
    'AGENCE EL OUARDIA (57)                ',
    'AGENCE RUE DE SYRIE (58)              ',
    'AG. AVENUE HABIB BOURGUIBA IV (59)    ',
    'AGENCE AVENUE DE FRANCE (60)          ',
    'AG. COMPTOIR DES PARTICULIERS (61)    ',
    'AGENCE AVENUE DE PARIS I (62)         ',
    'AGENCE RUE EL JAZIRA I (63)           ',
    'AGENCE CHARGUIA (64)                  ',
    'AGENCE MED V PME (65)                 ',
    'AGENCE LAFAYETTE PP (66)              ',
    'AGENCE EL MENZEH I (67)               ',
    'AGENCE EL MENZEH VI (68)              ',
    'AGENCE AVENUE DE CARTHAGE (69)        ',
    'AG. EL MENZEH VII CITE LATIF (70)     ',
    'AGENCE INTERNATIONALE (71)            ',
    'AGENCE MANNOUBA (72)                  ',
    'AGENCE BEN AROUS (73)                 ',
    'AGENCE AVENUE HEDI CHAKER (74)        ',
    'AGENCE LE KRAM (75)                   ',
    'AGENCE ARIANA LE FORUM (76)           ',
    'AGENCE LE BARDO (77)                  ',
    'AGENCE RUE EL JAZIRA II (78)          ',
    'AGENCE TUNIS MEDINA (79)              ',
    'AGENCE JENDOUBA (80)                  ',
    'AGENCE ENNASR (A1)                    ',
    'AGENCE ALYSSA (A2)                    ',
    'AGENCE HAMMAMET CENTRE CELOTO (A3)    ',
    'AGENCE HAMMAMET MREZGA (A4)           ',
    'AGENCE DU PERSONNEL (A5)              ',
    'AGENCE SOUSSE MEDINA (A6)             ',
    'AG. LES JARDINS DEL KANTAOUI (A7)     ',
    'AGENCE MOHAMED V (A8+65)              ',
    'AGENCE MANARET EL HAMMAMET (A9)       ',
    'AGENCE EZZAHROUNI (B1)                ',
    'AGENCE HAMMAM LIF (B2)                ',
    'AGENCE CARNOY (B3)                    ',
    'AG. LES JARDINS DE LARIANA II (B4)    ',
    'AGENCE LAFAYETTE PME (B5)             ',
    'AGENCE MARSA (B6)                     ',
    'AGENCE SFAX JEDIDA (B7)               ',
    'AGENCE ARIANA NORD (B8)               ',
    'AGENCE MARINA HAMMAMET (B9)           ',
    'AGENCE MAHDIA II (C1)                 ',
    'AGENCE SAKIET EDDAIER (C2)            ',
    'AGENCE SFAX ROUTE EL AIN (C3)         ',
    'AGENCE EL BOUHAIRA (C4)               ',
    'AGENCE DJERBA MIDOUNE (C5)            ',
    'AGENCE TUNIS CITY (C6)                ',
    'AGENCE MONASTIR II (C7)               ',
    'AGENCE SOUSSE BELHOUANE (C8)          ',
    'AGENCE ENNASR II (C9)                 ',
    'AGENCE CITE DES SCIENCES (D1)         ',
    'AGENCE MARINA HAMMAMET (D2)           ',
    'AGENCE SOUSSE HACHED (D3)             ',
    'AGENCE SFAX ROUTE DE TUNIS (D4)       ',
    'AGENCE JEMMAL (D5)                    ',
    'AGENCE ZARZIS (D6)                    ',
    'AGENCE MONTPLAISIR (D7)               ',
    'AGENCE SFAX ROUTE DE TENIOUR (D8)     ',
    'AGENCE EL FAHS (D9)                   ',
    'AGENCE SFAX RUE 18 JANVIER (K1)       ',
    'AGENCE MGHIRA (K2)                    ',
    'AGENCE SAHLINE (K3)                   ',
    'AGENCE MENZEL JEMMIL (K4)             ',
    'AGENCE SOUSSE SAHLOUL (K5)            ',
    'AGENCE MOKNINE (K6)                   ',
    'AGENCE SIDI BOUSAID (K7)              ',
    'AGENCE MENZEL BOURGUIBA (K8)          ',
    'AGENCE MARSA II (K9)                  ',
    'AGENCE MENZEL TEMIME (L1)             ',
    'AGENCE DAR CHAABANE EL FEHRI (L2)     ',
    'AGENCE KELIBIA (L3)                   ',
    'AGENCE SOUKRA (L4)                    ',
    'AGENCE OUED ELLIL (L5)                ',
    'AGENCE EL KEF (L6)                    ',
    'AGENCE EZZAHRA (L7)                   ',
    'AGENCE BOUMHEL (L8)                   ',
    'AGENCE ENNFIDHA-AEROPORT (L9)         ',
    'AGENCE RAOUED/EL GHAZALA (M1)         ',
    'AGENCE KASSERINE (M2)                 ',
    'AGENCE EL MOUROUJ IV (M3)             ',
    'AGENCE LES JARDINS DU LAC (M4)        ',
    'AGENCE HAMMAM SOUSSE- MENCHIA (M5)    ',
    'AGENCE EL MENZAH 9 (M6)               ',
    'AGENCE SOLIMAN (M7)                   ',
    'AGENCE SOUSSE SIDI ABDELHAMID (M8)    ',
    'AGENCE AIN ZAGHOUAN (M9)              ',
    'AGENCE LAOUINA (N1)                   ',
    'AGENCE CITE EL KHADRA (N2)            ',
    'AGENCE CITE ETTADHAMEN (N3)           ',
    'AGENCE SFAX-ETTOUTA (N4)              ',
    'AGENCE SILIANA (N5)                   ',
    'AGENCE SIDI BOUZID (N6)               ',
    'AGENCE NABEUL-OUED SOUHIL (N7)        ',
    'AGENCE SIDI HASSINE (N8)              ',
    'AGENCE BAB BNET (N9)                  ',
    'AGENCE LES JARDINS D EL MENZAH (P1)   ',
    'AGENCE GAFSA (P2)                     ',
    'AGENCE BIZERTE CORNICHE (P3)          ',
    'AGENCE RADES (P4)                     ',
    'AGENCE IBN KHALDOUN (P5)              ',
    'AGENCE GABES 2 (P6)                   ',
    'AGENCE KSAR HELLAL 2 (P7)             ',
    'AGENCE SOUSSE ERRIADH (P8)            ',
    'AGENCE SAYADA (P9)                    ',
    'AGENCE BOUSALEM (R1)                  ',
    'AGENCE OUERDANINE (R2)                ',
    'AGENCE REGUEB (R3)                    ',
    'AGENCE MONFLEURY (R4)                 ',
    'AGENCE RAS JEBEL (R5)                 ',
    'AGENCE KALAA KEBIRA (R6)              ',
    'AGENCE BENI KHALLED (R7)              ',
    'AGENCE MEDENINE (R8)                  ',
    'AGENCE NOUVELLE MEDINA (R9)           ',
    'AG SFAX ROUTE MENZEL CHAKER (S1)      ',
    'AGENCE KSOUR ESSEF (S2)               ',
    'AGENCE MORNAG (S3)                    ',
    'AGENCE KEBILI (S4)                    ',
    'AGENCE GAMMARTH (S5)                  ',
    'AGENCE CHEBBA (S6)                    ',
    'AGENCE SFAX RT LAFRANE (S7)           ',
    'AGENCE BORJ LOUZIR (S8)               ',
    'AGENCE DENDEN (S9)                    ',
    'AGENCE EL JEM (T1)                    ',
    'AGENCE ZAGHOUAN (T2)                  ',
    'AGENCE TESTOUR (T3)                   ',
    'AGENCE BORJ CEDRIA (T4)               ',
    'AGENCE TEBOURBA (T5)                  ',
    'AGENCE TAJEROUINE (T6)                ',
    'AGENCE LA GOULETTE (T7)               ',
    'AGENCE MEDJEZ EL BAB (T8)             ',
    'AGENCE TATAOUINE (T9)                 ',
    'AGENCE AKOUDA (U1)                    ',
    'AGENCE CITE EZZOUHOUR (U2)            ',
    'AGENCE ENFIDHA VILLE (U3)             ',
    'AGENCE SOUASSI (U4)                   ',
    'AGENCE SFAX RT SALTNIA (U5)           ',
    'AG JARDINS DE CARTHAGE (U6)           ',
    'AGENCE MONCEF BEY (U7)                ',
    'AGENCE MONASTIR III (U8)              ',
    'AGENCE SAHLOUL 2 (U9)                 ',
    'AGENCE SOUK LAHAD (V1)                ',
    'AGENCE MORNAGUIA (V2)                 ',
    'AGENCE YASMINET (V3)                  ',
    'AGENCE MHAMDIA (V4)                   ',
    'AGENCE BARDO II (V5)                  ',
  ];

  constructor(
    private _fb: FormBuilder,
    private _clService: ClientService,
    private _dialogRef: MatDialogRef<ClAddEditComponent>,
    @Inject(MAT_DIALOG_DATA) public data: any,
    private _coreService: CoreService
  ) {
    this.clForm = this._fb.group({
      Prenom: '',
      Nom: '',
      dob: '',
      email: '',
      IndicatifPays: '',
      NumTel: '',
      CIN: '',
      agence: '',
      Identifiant: '',
      MDP: '',
      solde: '',
    });
  }

  ngOnInit(): void {
    this.clForm.patchValue(this.data);
  }

  onFormSubmit() {
    if (this.clForm.valid) {
      if (this.data) {
        this._clService
          .updateClient(this.data.id, this.clForm.value)
          .subscribe({
            next: (val: any) => {
              this._coreService.openSnackBar('Client detail updated!');
              this._dialogRef.close(true);
            },
            error: (err: any) => {
              console.error(err);
            },
          });
      } else {
        this._clService.addClient(this.clForm.value).subscribe({
          next: (val: any) => {
            this._coreService.openSnackBar('Client added successfully');
            this._dialogRef.close(true);
          },
          error: (err: any) => {
            console.error(err);
          },
        });
      }
    }
  }
}
